name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'docs/**'
      - 'docfx.json'
      - 'index.md'
      - 'toc.yml'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for git info
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Install DocFX
        run: dotnet tool install -g docfx
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build projects
        run: dotnet build --no-restore --configuration Release
      
      - name: Generate API metadata
        run: docfx metadata docfx.json
      
      - name: Build documentation
        run: docfx build docfx.json
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
