name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'docs/**'
      - 'docfx.json'
      - 'index.md'
      - 'toc.yml'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Full history for git info
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      
      - name: Install DocFX
        run: dotnet tool install -g docfx
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build projects
        run: dotnet build --no-restore --configuration Release
      
      - name: Generate API metadata
        run: docfx metadata docfx.json
      
      - name: Build documentation
        run: docfx build docfx.json
      
      - name: Prepare GitHub Pages deployment
        run: |
          # Add .nojekyll to prevent Jekyll processing
          touch _site/.nojekyll
          
          cd _site
          
          # Remove INDEX.md from tracking if it exists
          rm -f INDEX.md
          
          # Ensure lowercase index.html exists (DocFX should generate this from index.md)
          if [ ! -f index.html ]; then
            echo "⚠️  index.html not found, checking for alternatives..."
            ls -la *.html 2>/dev/null || true
            
            # If README.html exists but not index.html, use it as index
            if [ -f README.html ] && [ ! -f index.html ]; then
              echo "Using README.html as index.html"
              cp README.html index.html
            else
              echo "ERROR: No suitable index file found"
              exit 1
            fi
          fi
          
          # Move index.json to data folder to avoid conflicts
          if [ -f index.json ]; then
            mkdir -p data
            mv index.json data/index.json
          fi
          
          echo "✅ GitHub Pages deployment prepared"
          echo "Root HTML files:"
          ls -la *.html 2>/dev/null || echo "No HTML files found"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
